/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#464555",
        "tertiary-container": "#006e4b",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dae2fd",
        "on-primary-fixed": "#0f0069",
        "on-secondary-container": "#5c647a",
        "on-primary-container": "#dad7ff",
        "primary": "#3525cd",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline": "#777587",
        "on-secondary-fixed": "#131b2e",
        "primary-container": "#4f46e5",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#67f4b7",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-surface": "#2d3133",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#002113",
        "surface-container-highest": "#e0e3e5",
        "secondary": "#565e74",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#e2dfff",
        "surface-container": "#eceef0",
        "tertiary": "#005338",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        "secondary-container": "#dae2fd",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "outline-variant": "#c7c4d8",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#3323cc",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "xl": "64px",
        "base": "4px",
        "xs": "8px",
        "margin-mobile": "16px",
        "sm": "16px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "lg": "40px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
