"""Static demo datasets for the integration-test seed.

Content only — every entity is described here by its business data, and
``app/seed.py`` turns these into real rows (assigning UUIDs, Supabase user
IDs, timestamps, and derived analytics at runtime). Keeping the datasets in a
separate module keeps the seed logic readable and lets an operator edit or
extend the demo content without touching the seed flow.

Materials carry ``content`` (synthetic academic paragraphs). Those paragraphs
are what ``--with-rag`` embeds into Qdrant so Chat answers and Flashcard
generation resolve real citations. The seed never embeds materials whose
``status`` is not ``ready``.
"""

# ── People ─────────────────────────────────────────────────────────────────────

TEACHERS = [
    {
        "email": "teacher1@examai.com",
        "name": "Dr. Alice Smith",
        "role": "teacher",
    },
    {
        "email": "teacher2@examai.com",
        "name": "Dr. Bob Jones",
        "role": "teacher",
    },
    {
        "email": "teacher3@examai.com",
        "name": "Dr. Carol Nguyen",
        "role": "teacher",
    },
    {
        "email": "teacher4@examai.com",
        "name": "Dr. Dana Patel",
        "role": "teacher",
    },
]

# student1 / student2 keep their original names so the Phase 2–5 README
# credentials remain valid; the rest are realistic demo students.
STUDENTS = [
    {"email": "student1@examai.com", "name": "Charlie Student"},
    {"email": "student2@examai.com", "name": "Diana Student"},
    {"email": "student3@examai.com", "name": "Alex Martinez"},
    {"email": "student4@examai.com", "name": "Priya Mehta"},
    {"email": "student5@examai.com", "name": "Jordan Rivera"},
    {"email": "student6@examai.com", "name": "Kevin Lee"},
    {"email": "student7@examai.com", "name": "Sofia Rossi"},
    {"email": "student8@examai.com", "name": "Liam O'Connor"},
    {"email": "student9@examai.com", "name": "Emma Thompson"},
    {"email": "student10@examai.com", "name": "Noah Kim"},
    {"email": "student11@examai.com", "name": "Isabella Costa"},
    {"email": "student12@examai.com", "name": "Ethan Brooks"},
    {"email": "student13@examai.com", "name": "Mia Andersen"},
    {"email": "student14@examai.com", "name": "Lucas Meyer"},
    {"email": "student15@examai.com", "name": "Ava Fernandez"},
    {"email": "student16@examai.com", "name": "Oliver Schmidt"},
    {"email": "student17@examai.com", "name": "Zara Hussain"},
    {"email": "student18@examai.com", "name": "James Carter"},
    {"email": "student19@examai.com", "name": "Elena Petrova"},
    {"email": "student20@examai.com", "name": "Daniel Osei"},
    {"email": "student21@examai.com", "name": "Grace Kim"},
    {"email": "student22@examai.com", "name": "Mateo Silva"},
    {"email": "student23@examai.com", "name": "Layla Ahmed"},
    {"email": "student24@examai.com", "name": "Ryan Patel"},
    {"email": "student25@examai.com", "name": "Hannah Dubois"},
    {"email": "student26@examai.com", "name": "Tom Nguyen"},
]

# ── Subjects & membership ──────────────────────────────────────────────────────

SUBJECTS = [
    "Software Engineering",
    "Advanced Database Systems",
    "Data Structures & Algorithms",
    "Operating Systems",
]

# Every subject has two co-teachers (multi-teacher is load-bearing).
SUBJECT_TEACHERS = {
    "Software Engineering": ["teacher1@examai.com", "teacher2@examai.com"],
    "Advanced Database Systems": ["teacher1@examai.com", "teacher3@examai.com"],
    "Data Structures & Algorithms": ["teacher2@examai.com", "teacher4@examai.com"],
    "Operating Systems": ["teacher3@examai.com", "teacher4@examai.com"],
}

# Explicit enrollment sets: 16–17 students per subject, each student in 2–3
# subjects. Kept hand-written so the demo roster is predictable.
SUBJECT_ENROLLMENTS = {
    "Software Engineering": [
        f"student{i}@examai.com" for i in range(1, 17)
    ],
    "Advanced Database Systems": [
        "student2@examai.com", "student5@examai.com", "student6@examai.com",
        "student7@examai.com", "student9@examai.com", "student10@examai.com",
        "student12@examai.com", "student13@examai.com", "student14@examai.com",
        "student15@examai.com", "student17@examai.com", "student18@examai.com",
        "student19@examai.com", "student20@examai.com", "student21@examai.com",
        "student22@examai.com", "student23@examai.com",
    ],
    "Data Structures & Algorithms": [
        "student1@examai.com", "student3@examai.com", "student4@examai.com",
        "student6@examai.com", "student8@examai.com", "student9@examai.com",
        "student11@examai.com", "student12@examai.com", "student14@examai.com",
        "student16@examai.com", "student18@examai.com", "student20@examai.com",
        "student22@examai.com", "student24@examai.com", "student25@examai.com",
        "student26@examai.com",
    ],
    "Operating Systems": [
        "student2@examai.com", "student4@examai.com", "student5@examai.com",
        "student7@examai.com", "student8@examai.com", "student10@examai.com",
        "student11@examai.com", "student13@examai.com", "student15@examai.com",
        "student17@examai.com", "student19@examai.com", "student21@examai.com",
        "student23@examai.com", "student24@examai.com", "student25@examai.com",
        "student26@examai.com",
    ],
}

# ── Materials (metadata + synthetic content for RAG) ───────────────────────────

# `content` paragraphs are only used by `--with-rag`. `failed`/`processing`
# rows deliberately have no content and are never embedded.
MATERIALS = [
    # ── Software Engineering (co-taught: t1 + t2) ──────────────────────────
    {
        "subject": "Software Engineering",
        "teacher": "teacher1@examai.com",
        "filename": "lecture1_intro_se.pdf",
        "file_type": "pdf",
        "display_name": "Lecture 1 — Intro to Software Engineering",
        "notes": "Introduces the software development lifecycle and process models.",
        "status": "ready",
        "content": [
            "Software engineering is the systematic application of engineering approaches to the development, operation, and maintenance of software. Unlike a purely programming exercise, it emphasizes disciplined processes, clear documentation, and measurable quality so that large systems can be built by teams over long periods of time.",
            "Most software projects follow a lifecycle that moves through phases: requirements analysis, design, implementation, testing, and maintenance. Each phase produces artifacts that feed the next one, and the transition rules between phases depend on the chosen process model.",
            "Plan-driven approaches complete requirements and design documentation before implementation begins. This works well when requirements are stable and the problem is well understood, because early mistakes can be caught while they are still cheap to fix.",
            "Agile approaches, by contrast, deliver working software in short increments and adapt the plan based on feedback. They trade the predictability of a detailed upfront plan for flexibility in the face of changing requirements.",
            "Software quality attributes such as maintainability, reliability, security, and performance are first-class concerns. A system that works on day one but cannot be changed without breaking is not maintainable, and maintainability is often the attribute that determines long-term cost.",
            "Stakeholders are the people and organizations with an interest in the project: clients, end users, managers, and regulators. Understanding who they are and what they value shapes both the requirements and the way the team reports progress.",
        ],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher2@examai.com",
        "filename": "lecture2_agile_scrum.pdf",
        "file_type": "pdf",
        "display_name": "Lecture 2 — Agile & Scrum",
        "notes": "Covers the Agile Manifesto, Scrum roles, events, and artifacts.",
        "status": "ready",
        "content": [
            "The Agile Manifesto values individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, and responding to change over following a plan. The value of these preferences is that they keep the team focused on delivering value.",
            "Agile principles include delivering working software frequently, welcoming changing requirements, and reflecting on how to become more effective at regular intervals. Continuous improvement is built into the process rather than being an afterthought.",
            "Scrum defines three roles: the Product Owner owns the product backlog and prioritizes value, the Scrum Master facilitates the process and removes impediments, and the development team self-organizes to deliver increments of the product.",
            "Scrum events are the sprint, sprint planning, the daily stand-up, the sprint review, and the sprint retrospective. A sprint is a time-boxed iteration, usually one to four weeks, at the end of which the team has a potentially releasable increment.",
            "The main Scrum artifacts are the product backlog, the sprint backlog, and the increment. The product backlog is a prioritized list of everything that might be needed; the sprint backlog is the subset the team commits to in the current sprint.",
            "Engineering practices like continuous integration and continuous delivery support agility by keeping the codebase always buildable. Frequent integration catches integration defects early and makes each increment genuinely releasable.",
        ],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher1@examai.com",
        "filename": "lecture3_requirements.pdf",
        "file_type": "pdf",
        "display_name": "Lecture 3 — Requirements Engineering",
        "notes": "Functional vs non-functional requirements, user stories, acceptance criteria.",
        "status": "ready",
        "content": [
            "Requirements engineering is the process of discovering, analyzing, documenting, and validating what a system must do. Poor requirements are the leading cause of failed projects, because a misunderstanding at this stage propagates into every later phase.",
            "Functional requirements describe behaviors the system must provide, such as letting a user log in or generating a report. Non-functional requirements constrain how the system behaves, such as responding within 200 milliseconds or protecting data with encryption.",
            "User stories are a compact way to capture functional requirements: As a <role>, I want <goal> so that <benefit>. The benefit clause makes the underlying business value explicit and helps the team prioritize.",
            "Acceptance criteria turn a vague story into testable conditions that must hold for the story to be considered done. Well-written criteria are unambiguous, verifiable, and specific enough that both the team and the customer can agree on completion.",
            "Elicitation techniques include interviews, workshops, surveys, and observation. Choosing the right technique depends on the stakeholders involved and how explicit the desired knowledge is.",
            "Traceability links requirements to design decisions, test cases, and code, so a change to one requirement can be assessed for its impact. A requirements traceability matrix is a common tool for managing these links.",
        ],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher2@examai.com",
        "filename": "lab1_uml_diagrams.pdf",
        "file_type": "pdf",
        "display_name": "Lab 1 — UML Diagrams",
        "notes": "Class and sequence diagram notation. (Processing — not yet queryable.)",
        "status": "processing",
        "content": [],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher1@examai.com",
        "filename": "lecture4_testing.pdf",
        "file_type": "pdf",
        "display_name": "Lecture 4 — Software Testing",
        "notes": "Test levels, unit/integration/system testing, TDD. (Ingestion failed.)",
        "status": "failed",
        "content": [],
    },

    # ── Advanced Database Systems (co-taught: t1 + t3) ─────────────────────
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher1@examai.com",
        "filename": "ch1_relational_algebra.pdf",
        "file_type": "pdf",
        "display_name": "Ch 1 — Relational Model & Algebra",
        "notes": "Relations, keys, selection, projection, joins, set operations.",
        "status": "ready",
        "content": [
            "The relational model organizes data into relations, which are conceptually tables of rows and named columns. Every row, or tuple, is unique, and the order of rows and columns carries no meaning in the model itself.",
            "Keys are the backbone of relational integrity. A candidate key uniquely identifies each tuple, one candidate key is chosen as the primary key, and a foreign key in one relation references the primary key of another, enforcing referential integrity.",
            "Selection, written sigma, filters rows of a relation by a predicate, returning the subset of tuples that satisfy it. Selection reduces the number of rows but never the number of columns.",
            "Projection, written pi, selects a subset of columns and removes duplicate rows. Projection reduces the width of a relation and is used to answer which-attribute questions.",
            "Joins combine columns from two relations based on a condition. A theta join uses an arbitrary comparison predicate, while a natural join equates the equally named columns and removes the duplicate join column.",
            "Set operations such as union, intersection, and set difference treat relations as sets of tuples. These operations require the two relations to be union-compatible, meaning they have the same number and type of attributes.",
        ],
    },
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher3@examai.com",
        "filename": "ch2_query_optimization.pdf",
        "file_type": "pdf",
        "display_name": "Ch 2 — Query Optimization",
        "notes": "Cost-based plans, statistics, indexes, join strategies, rewrites.",
        "status": "ready",
        "content": [
            "A query optimizer turns a declarative SQL statement into an execution plan: a tree of operators such as scans, joins, filters, and sorts. The optimizer's job is to pick the cheapest plan it can find among the many equivalent ones.",
            "Cost estimation relies on statistics about the data: table cardinality, the number of distinct values in columns, and histograms of value distributions. Stale statistics are a common reason an optimizer picks a bad plan.",
            "Indexes give the executor a fast path to a small fraction of a table. A B-tree index supports both equality and range lookups in logarithmic time, while a hash index supports only equality lookups.",
            "Join strategies trade off memory, CPU, and I/O. A nested-loop join scans the inner relation once per outer row, a sort-merge join is useful on presorted inputs, and a hash join builds a hash table on the smaller input for efficient equi-joins.",
            "Rewrites such as predicate pushdown move filters as early as possible in the plan, shrinking the data that later operators must process. Choosing the join order that minimizes intermediate result sizes is another powerful rewrite.",
            "An EXPLAIN plan exposes the operators the optimizer selected, their order, and estimated costs. Reading plans is the primary skill for diagnosing slow queries in practice.",
        ],
    },
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher3@examai.com",
        "filename": "ch3_transactions_concurrency.pdf",
        "file_type": "pdf",
        "display_name": "Ch 3 — Transactions & Concurrency",
        "notes": "ACID, isolation levels, locking, two-phase locking, recovery.",
        "status": "ready",
        "content": [
            "A transaction is a sequence of operations that must be treated as an atomic unit of work. The ACID properties — atomicity, consistency, isolation, and durability — define the guarantees a transaction manager provides.",
            "Atomicity means the whole transaction commits or the whole transaction rolls back, even if a crash happens mid-way. Consistency means the database moves from one valid state to another, preserving constraints.",
            "Isolation controls how concurrently executing transactions see each other's changes. The SQL isolation levels are read uncommitted, read committed, repeatable read, and serializable, each trading strictness for concurrency.",
            "Locking is the standard mechanism for isolation. Two-phase locking guarantees conflict serializability: a transaction acquires all its locks before releasing any of them, in a growing phase followed by a shrinking phase.",
            "Deadlock occurs when two transactions each hold a lock the other needs and neither can proceed. Databases detect deadlocks and abort one victim transaction, rolling it back so the other can finish.",
            "Recovery is based on write-ahead logging: changes are logged before they are applied, so after a crash the database can replay committed work and undo uncommitted work to restore a durable, consistent state.",
        ],
    },

    # ── Data Structures & Algorithms (co-taught: t2 + t4) ──────────────────
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher2@examai.com",
        "filename": "week1_arrays_complexity.pdf",
        "file_type": "pdf",
        "display_name": "Week 1 — Arrays & Complexity",
        "notes": "Big-O notation, contiguous arrays, amortized analysis, binary search.",
        "status": "ready",
        "content": [
            "Big-O notation describes how the running time or memory of an algorithm grows with the size of its input. It measures worst-case growth and ignores constant factors, so O(2n) and O(1000n) are both written O(n).",
            "An array stores elements contiguously in memory, which gives random access: reading or writing any element by index costs constant time, O(1). This is the defining advantage of arrays over pointer-based structures.",
            "Insertion and deletion in the middle of an array cost O(n) because the elements after the operation point must be shifted to preserve contiguity. Resizing is also costly, but it happens rarely when the array grows geometrically.",
            "A dynamic array that doubles its capacity when full has amortized O(1) appends: the occasional O(n) resize is paid for by the many O(1) appends before it. Amortized analysis averages the cost of one operation over a sequence.",
            "Binary search repeatedly halves the search range and therefore runs in O(log n) time, but it requires the array to be sorted. It is exponentially faster than linear search for large inputs.",
            "Common complexity classes, from fastest to slowest, are O(1), O(log n), O(n), O(n log n), O(n squared), and O(2 to the n). Choosing an algorithm in the right class is usually more important than micro-optimizing constants.",
        ],
    },
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher4@examai.com",
        "filename": "week2_linkedlists_stacks.pdf",
        "file_type": "pdf",
        "display_name": "Week 2 — Linked Lists, Stacks & Queues",
        "notes": "Singly/doubly linked lists, LIFO stacks, FIFO queues, cycle detection.",
        "status": "ready",
        "content": [
            "A singly linked list is a sequence of nodes, each storing a value and a pointer to the next node. Traversal must start at the head and follow pointers, so indexing the k-th element costs O(n).",
            "A doubly linked list stores both next and previous pointers, which enables O(1) deletion of a node once you have a pointer to it. The trade-off is one extra pointer per node and more careful pointer updates.",
            "Inserting or deleting at the head of a linked list is O(1), because only the head pointer and one node need to change. This makes linked lists attractive for stacks, where all operations happen at one end.",
            "A stack is a last-in-first-out structure supporting push and pop, both O(1). Stacks back function-call machinery, undo history in editors, and expression evaluation via postfix notation.",
            "A queue is a first-in-first-out structure supporting enqueue at the tail and dequeue at the head, both O(1). Queues are used for breadth-first search, request buffering, and fair task scheduling.",
            "Detecting a cycle in a linked list is classically done with Floyd's tortoise-and-hare algorithm: two pointers advance at different speeds, and if they ever meet, a cycle exists. The technique uses only constant extra space.",
        ],
    },
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher4@examai.com",
        "filename": "week3_trees_graphs.pdf",
        "file_type": "pdf",
        "display_name": "Week 3 — Trees & Graphs",
        "notes": "Binary trees, BSTs, traversals, adjacency representations, BFS/DFS.",
        "status": "ready",
        "content": [
            "A tree is a connected, acyclic graph. A binary tree is a tree in which every node has at most two children, typically named left and right, making it a natural basis for search and hierarchical data.",
            "In a binary search tree, every node's left subtree contains only values less than the node and its right subtree only values greater. Search, insertion, and deletion therefore take O(log n) time on a balanced BST.",
            "Traversals visit nodes in defined orders: preorder visits a node before its children, inorder visits left, node, right, and postorder visits children first. An inorder traversal of a BST visits its values in sorted order.",
            "Unbalanced trees can degrade to a linked list with O(n) operations, which is why balanced structures such as AVL trees and red-black trees rebalance after inserts and deletes to preserve the logarithmic guarantee.",
            "Graphs are represented either as adjacency lists, one list of neighbors per vertex, or as adjacency matrices, a V by V boolean grid. Adjacency lists use far less memory for sparse graphs and iterate neighbors faster.",
            "Breadth-first search visits vertices in order of distance from the source and uses a queue, while depth-first search explores as far as possible down each branch and uses a stack or recursion. Both run in O(V + E) on adjacency lists.",
        ],
    },

    # ── Operating Systems (co-taught: t3 + t4) ─────────────────────────────
    {
        "subject": "Operating Systems",
        "teacher": "teacher3@examai.com",
        "filename": "lec1_processes_threads.pdf",
        "file_type": "pdf",
        "display_name": "Lec 1 — Processes & Threads",
        "notes": "Process states, PCBs, context switching, threads vs processes.",
        "status": "ready",
        "content": [
            "A process is a program in execution, with its own address space, registers, open files, and an associated process control block. The PCB is the OS data structure that stores this state so the process can be resumed later.",
            "A process moves through states: new, ready, running, blocked, and terminated. Transitions are driven by the scheduler and by events such as I/O completion, so the set of states forms a well-defined state machine.",
            "A context switch happens when the CPU is taken from one process and given to another: the kernel saves the outgoing process's registers and program counter and restores the incoming process's. Switching is overhead, so schedulers try to avoid excessive switching.",
            "Threads are lighter-weight execution units that share the address space of their process. Because they share memory, threads can communicate without kernel involvement, but they must synchronize to avoid data races.",
            "Creating a thread is cheaper than creating a process because no new address space is needed; the kernel only allocates a stack and register context. This is why thread pools are common in server workloads.",
            "Processes communicate through inter-process communication mechanisms such as pipes, message queues, shared memory, and sockets. Shared memory is fastest but requires explicit synchronization, while message passing is safer but slower.",
        ],
    },
    {
        "subject": "Operating Systems",
        "teacher": "teacher4@examai.com",
        "filename": "lec2_cpu_scheduling.pdf",
        "file_type": "pdf",
        "display_name": "Lec 2 — CPU Scheduling",
        "notes": "FCFS, SJF, round robin, priority scheduling, starvation, multilevel queues.",
        "status": "ready",
        "content": [
            "The CPU scheduler selects which ready process runs next. It maintains a ready queue of processes that are ready to execute and waiting only for the CPU, and a dispatch decision is made on events such as process arrival, I/O completion, and timer interrupts.",
            "First-come-first-served scheduling runs processes in arrival order and is non-preemptive. Its convoy effect, where short jobs wait behind a long one, makes average waiting time poor.",
            "Shortest-job-first scheduling runs the process with the shortest next CPU burst and provably minimizes average waiting time. The preemptive variant, shortest-remaining-time-first, is optimal in the same sense for arrival-order fairness.",
            "Round-robin scheduling gives every process a fixed time slice, the time quantum, and then cycles to the next. It is fair and preemptive; a very small quantum increases context-switch overhead while a large quantum degrades responsiveness.",
            "Priority scheduling runs the highest-priority ready process, but low-priority processes can starve if higher-priority work keeps arriving. Aging gradually raises the priority of waiting processes to prevent starvation.",
            "Multilevel feedback queues partition processes into queues with different policies and allow movement between them, letting short interactive jobs get fast service while long compute jobs still make progress.",
        ],
    },
    {
        "subject": "Operating Systems",
        "teacher": "teacher4@examai.com",
        "filename": "lec3_memory_management.pdf",
        "file_type": "pdf",
        "display_name": "Lec 3 — Memory Management",
        "notes": "Paging, page tables, virtual memory, page replacement, thrashing.",
        "status": "ready",
        "content": [
            "Paging divides physical memory into fixed-size frames and virtual memory into matching pages. A page table maps each virtual page to a physical frame, letting processes run in non-contiguous physical memory.",
            "The translation lookaside buffer caches recent page-table entries so that address translation usually avoids a memory access. TLB hits make paged access nearly as fast as contiguous access.",
            "Virtual memory lets a process use more address space than physical RAM by keeping only active pages resident. Demand paging loads a page only when it is referenced, so programs can run while much of their code sits on disk.",
            "When memory is full, a page replacement algorithm picks a victim page to evict. FIFO is simple but can exhibit Belady's anomaly, where adding more frames increases page faults; LRU approximates optimal replacement.",
            "Thrashing occurs when the working set of active processes exceeds physical memory and the system spends more time paging than executing. The classic cure is reducing the degree of multiprogramming or shrinking working sets.",
            "Memory management integrates with scheduling: a process cannot run until its working set is resident, so the OS coordinates paging and process admission to keep the memory subsystem from thrashing.",
        ],
    },
]

# ── Quizzes (teacher-authored, shared across the class) ───────────────────────

QUIZZES = [
    # Software Engineering
    {
        "subject": "Software Engineering",
        "teacher": "teacher1@examai.com",
        "topic": "Software Engineering Fundamentals",
        "source": "manual",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "What is the correct order of the classic software development lifecycle phases?",
                "options": [
                    "Requirements, Design, Implementation, Testing, Maintenance",
                    "Design, Requirements, Implementation, Testing, Maintenance",
                    "Implementation, Design, Requirements, Testing, Maintenance",
                    "Requirements, Implementation, Design, Testing, Maintenance",
                ],
                "correct_option": "Requirements, Design, Implementation, Testing, Maintenance",
                "topic_tag": "SDLC",
                "difficulty": "easy",
            },
            {
                "question_text": "In a plan-driven development process, the requirements document is typically…",
                "options": [
                    "Completed before implementation begins",
                    "Written during the testing phase",
                    "Created after deployment",
                    "Never produced formally",
                ],
                "correct_option": "Completed before implementation begins",
                "topic_tag": "SDLC",
                "difficulty": "medium",
            },
            {
                "question_text": "Which of the following is a non-functional requirement?",
                "options": [
                    "The system shall respond within 200 ms",
                    "The system shall allow users to log in",
                    "The system shall display order history",
                    "The system shall send an email receipt",
                ],
                "correct_option": "The system shall respond within 200 ms",
                "topic_tag": "Requirements",
                "difficulty": "easy",
            },
            {
                "question_text": "Which activity belongs to the design phase of the lifecycle?",
                "options": [
                    "Defining the module architecture",
                    "Writing user stories",
                    "Executing test cases",
                    "Collecting stakeholder feedback",
                ],
                "correct_option": "Defining the module architecture",
                "topic_tag": "SDLC",
                "difficulty": "medium",
            },
            {
                "question_text": "Why is early requirements validation important?",
                "options": [
                    "It reduces the cost of fixing defects",
                    "It removes the need for testing",
                    "It speeds up the maintenance phase",
                    "It eliminates the design phase",
                ],
                "correct_option": "It reduces the cost of fixing defects",
                "topic_tag": "Requirements",
                "difficulty": "medium",
            },
            {
                "question_text": "Which is an example of a functional requirement?",
                "options": [
                    "The system shall reset a user's forgotten password",
                    "The system shall encrypt passwords at rest",
                    "The system shall be available 99.9% of the time",
                    "The system shall support 10,000 concurrent users",
                ],
                "correct_option": "The system shall reset a user's forgotten password",
                "topic_tag": "Requirements",
                "difficulty": "easy",
            },
        ],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher2@examai.com",
        "topic": "Agile Development Practices",
        "source": "ai_generated",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "Which value is part of the Agile Manifesto?",
                "options": [
                    "Individuals and interactions over processes and tools",
                    "Comprehensive documentation over working software",
                    "Contract negotiation over customer collaboration",
                    "Following a plan over responding to change",
                ],
                "correct_option": "Individuals and interactions over processes and tools",
                "topic_tag": "Agile",
                "difficulty": "easy",
            },
            {
                "question_text": "In Scrum, who is responsible for removing impediments?",
                "options": ["Scrum Master", "Product Owner", "Development Team", "Stakeholders"],
                "correct_option": "Scrum Master",
                "topic_tag": "Scrum",
                "difficulty": "easy",
            },
            {
                "question_text": "A time-boxed iteration in Scrum is called a…",
                "options": ["Sprint", "Milestone", "Release", "Phase"],
                "correct_option": "Sprint",
                "topic_tag": "Scrum",
                "difficulty": "easy",
            },
            {
                "question_text": "Who owns and prioritizes the Product Backlog?",
                "options": ["Product Owner", "Scrum Master", "Development Team", "Project Sponsor"],
                "correct_option": "Product Owner",
                "topic_tag": "Scrum",
                "difficulty": "easy",
            },
            {
                "question_text": "Which practice emphasizes frequently merging and testing code changes?",
                "options": [
                    "Continuous Integration",
                    "Waterfall scheduling",
                    "Big-bang integration",
                    "Manual regression suites",
                ],
                "correct_option": "Continuous Integration",
                "topic_tag": "Practices",
                "difficulty": "medium",
            },
            {
                "question_text": "Which event is a short daily meeting to synchronize progress and blockers?",
                "options": [
                    "Daily stand-up",
                    "Sprint review",
                    "Sprint retrospective",
                    "Release planning",
                ],
                "correct_option": "Daily stand-up",
                "topic_tag": "Scrum",
                "difficulty": "easy",
            },
        ],
    },
    {
        "subject": "Software Engineering",
        "teacher": "teacher1@examai.com",
        "topic": "Requirements Engineering",
        "source": "manual",
        "status": "draft",
        "time_limit_seconds": 900,
        "questions": [
            {
                "question_text": "A user story follows which format?",
                "options": [
                    "As a <role>, I want <goal> so that <benefit>",
                    "Given <context>, when <event>, then <outcome>",
                    "The system shall <behavior> under <constraint>",
                    "IF <condition> THEN <action> ELSE <other action>",
                ],
                "correct_option": "As a <role>, I want <goal> so that <benefit>",
                "topic_tag": "Stories",
                "difficulty": "easy",
            },
            {
                "question_text": "Acceptance criteria are best described as…",
                "options": [
                    "Testable conditions a story must meet to be done",
                    "A prioritized list of all possible features",
                    "Design diagrams describing system structure",
                    "Performance targets for the final release",
                ],
                "correct_option": "Testable conditions a story must meet to be done",
                "topic_tag": "Stories",
                "difficulty": "medium",
            },
            {
                "question_text": "Which elicitation technique involves talking directly with stakeholders?",
                "options": ["Interviews", "Code review", "Debugging", "Load testing"],
                "correct_option": "Interviews",
                "topic_tag": "Elicitation",
                "difficulty": "easy",
            },
            {
                "question_text": "A requirements traceability matrix links requirements to…",
                "options": [
                    "Design, tests, and code",
                    "Team member salaries",
                    "Hardware procurement orders",
                    "Marketing campaign budgets",
                ],
                "correct_option": "Design, tests, and code",
                "topic_tag": "Traceability",
                "difficulty": "medium",
            },
            {
                "question_text": "\"The product shall handle 10,000 concurrent users\" is an example of a…",
                "options": [
                    "Non-functional requirement",
                    "Functional requirement",
                    "User story",
                    "Design pattern",
                ],
                "correct_option": "Non-functional requirement",
                "topic_tag": "Requirements",
                "difficulty": "easy",
            },
        ],
    },

    # Advanced Database Systems
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher1@examai.com",
        "topic": "Relational Algebra & SQL",
        "source": "manual",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "Which relational algebra operation filters rows by a predicate?",
                "options": ["Selection (σ)", "Projection (π)", "Union (∪)", "Cartesian product"],
                "correct_option": "Selection (σ)",
                "topic_tag": "Relational Algebra",
                "difficulty": "easy",
            },
            {
                "question_text": "Projection (π) returns…",
                "options": [
                    "A subset of the columns",
                    "A subset of the rows",
                    "The full table unchanged",
                    "Two tables combined side by side",
                ],
                "correct_option": "A subset of the columns",
                "topic_tag": "Relational Algebra",
                "difficulty": "easy",
            },
            {
                "question_text": "Which operation combines columns from two relations based on a condition?",
                "options": ["Join", "Selection", "Projection", "Aggregation"],
                "correct_option": "Join",
                "topic_tag": "Relational Algebra",
                "difficulty": "easy",
            },
            {
                "question_text": "In SQL, which clause filters rows after GROUP BY aggregation?",
                "options": ["HAVING", "WHERE", "LIMIT", "ORDER BY"],
                "correct_option": "HAVING",
                "topic_tag": "SQL",
                "difficulty": "medium",
            },
            {
                "question_text": "A primary key guarantees that rows are…",
                "options": [
                    "Unique and non-null on the key columns",
                    "Duplicated and nullable",
                    "Ordered by insertion time",
                    "Encrypted at rest",
                ],
                "correct_option": "Unique and non-null on the key columns",
                "topic_tag": "Keys",
                "difficulty": "easy",
            },
            {
                "question_text": "A foreign key enforces…",
                "options": [
                    "Referential integrity",
                    "Index uniqueness",
                    "Column immutability",
                    "Query result ordering",
                ],
                "correct_option": "Referential integrity",
                "topic_tag": "Keys",
                "difficulty": "easy",
            },
        ],
    },
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher3@examai.com",
        "topic": "Query Optimization",
        "source": "ai_generated",
        "status": "published",
        "time_limit_seconds": 900,
        "questions": [
            {
                "question_text": "What is the primary job of a query optimizer?",
                "options": [
                    "Choose the cheapest execution plan",
                    "Encrypt query results",
                    "Generate SQL syntax errors",
                    "Validate application business rules",
                ],
                "correct_option": "Choose the cheapest execution plan",
                "topic_tag": "Optimization",
                "difficulty": "easy",
            },
            {
                "question_text": "A B-tree index is well suited for…",
                "options": [
                    "Equality and range lookups",
                    "Storing unstructured text blobs",
                    "Replacing the transaction log",
                    "Only full table scans",
                ],
                "correct_option": "Equality and range lookups",
                "topic_tag": "Indexing",
                "difficulty": "medium",
            },
            {
                "question_text": "Which join algorithm scans the inner relation once per outer row?",
                "options": ["Nested-loop join", "Hash join", "Sort-merge join", "Index-union join"],
                "correct_option": "Nested-loop join",
                "topic_tag": "Join Strategies",
                "difficulty": "medium",
            },
            {
                "question_text": "What statistics does an optimizer use to estimate costs?",
                "options": [
                    "Table cardinality and column histograms",
                    "Application log levels",
                    "Network latency between clients",
                    "Query text length",
                ],
                "correct_option": "Table cardinality and column histograms",
                "topic_tag": "Statistics",
                "difficulty": "medium",
            },
            {
                "question_text": "A sequential scan is preferable to an index scan when…",
                "options": [
                    "Most rows of the table match",
                    "The table is fully cached in memory",
                    "The query has no WHERE clause at all",
                    "The table has no primary key",
                ],
                "correct_option": "Most rows of the table match",
                "topic_tag": "Optimization",
                "difficulty": "hard",
            },
            {
                "question_text": "Which is a query rewrite technique that improves plans?",
                "options": [
                    "Predicate pushdown",
                    "Adding an ORDER BY",
                    "Increasing query timeouts",
                    "Disabling indexes",
                ],
                "correct_option": "Predicate pushdown",
                "topic_tag": "Rewrites",
                "difficulty": "hard",
            },
        ],
    },
    {
        "subject": "Advanced Database Systems",
        "teacher": "teacher3@examai.com",
        "topic": "Transactions & Concurrency Control",
        "source": "manual",
        "status": "draft",
        "time_limit_seconds": 900,
        "questions": [
            {
                "question_text": "ACID stands for…",
                "options": [
                    "Atomicity, Consistency, Isolation, Durability",
                    "Availability, Consistency, Integrity, Durability",
                    "Atomicity, Compatibility, Isolation, Data-flow",
                    "Access, Consistency, Integrity, Deletion",
                ],
                "correct_option": "Atomicity, Consistency, Isolation, Durability",
                "topic_tag": "ACID",
                "difficulty": "easy",
            },
            {
                "question_text": "Which isolation level prevents dirty reads but allows non-repeatable reads?",
                "options": [
                    "Read Committed",
                    "Read Uncommitted",
                    "Serializable",
                    "Repeatable Read",
                ],
                "correct_option": "Read Committed",
                "topic_tag": "Isolation",
                "difficulty": "medium",
            },
            {
                "question_text": "Two-phase locking guarantees…",
                "options": [
                    "Conflict serializability",
                    "Lock-free execution",
                    "Faster I/O on every commit",
                    "Deadlock-free execution",
                ],
                "correct_option": "Conflict serializability",
                "topic_tag": "Locking",
                "difficulty": "medium",
            },
            {
                "question_text": "A deadlock occurs when…",
                "options": [
                    "Two transactions wait on locks each other holds",
                    "A transaction aborts due to a syntax error",
                    "The disk fills up mid-commit",
                    "A query returns more rows than expected",
                ],
                "correct_option": "Two transactions wait on locks each other holds",
                "topic_tag": "Deadlocks",
                "difficulty": "easy",
            },
            {
                "question_text": "Write-ahead logging is used primarily to ensure…",
                "options": [
                    "Durability and crash recovery",
                    "Query result caching",
                    "Schema migration safety",
                    "Connection pool reuse",
                ],
                "correct_option": "Durability and crash recovery",
                "topic_tag": "Recovery",
                "difficulty": "medium",
            },
        ],
    },

    # Data Structures & Algorithms
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher2@examai.com",
        "topic": "Arrays & Complexity",
        "source": "manual",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "What is the time complexity of accessing an array element by index?",
                "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
                "correct_option": "O(1)",
                "topic_tag": "Complexity",
                "difficulty": "easy",
            },
            {
                "question_text": "What is the worst-case time complexity of linear search over n elements?",
                "options": ["O(n)", "O(1)", "O(log n)", "O(n squared)"],
                "correct_option": "O(n)",
                "topic_tag": "Complexity",
                "difficulty": "easy",
            },
            {
                "question_text": "Amortized analysis of appending to a doubling dynamic array yields…",
                "options": ["O(1) amortized", "O(n) amortized", "O(log n) amortized", "O(n log n) amortized"],
                "correct_option": "O(1) amortized",
                "topic_tag": "Complexity",
                "difficulty": "medium",
            },
            {
                "question_text": "Inserting into the middle of a contiguous array costs…",
                "options": ["O(n)", "O(1)", "O(log n)", "O(1) amortized"],
                "correct_option": "O(n)",
                "topic_tag": "Arrays",
                "difficulty": "medium",
            },
            {
                "question_text": "Binary search requires the input array to be…",
                "options": ["Sorted", "Of even length", "Stored contiguously", "Free of duplicates"],
                "correct_option": "Sorted",
                "topic_tag": "Complexity",
                "difficulty": "easy",
            },
            {
                "question_text": "Which of the following is O(log n)?",
                "options": ["Binary search", "Linear search", "Bubble sort", "Nested loop over n"],
                "correct_option": "Binary search",
                "topic_tag": "Complexity",
                "difficulty": "easy",
            },
        ],
    },
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher4@examai.com",
        "topic": "Linked Lists, Stacks & Queues",
        "source": "ai_generated",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "A singly linked list node holds…",
                "options": [
                    "A value and a pointer to the next node",
                    "Only a value",
                    "A value and a pointer to the previous node",
                    "An index and a hash",
                ],
                "correct_option": "A value and a pointer to the next node",
                "topic_tag": "Linked Lists",
                "difficulty": "easy",
            },
            {
                "question_text": "Inserting at the head of a linked list is…",
                "options": ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
                "correct_option": "O(1)",
                "topic_tag": "Linked Lists",
                "difficulty": "easy",
            },
            {
                "question_text": "A stack exhibits which ordering?",
                "options": ["LIFO", "FIFO", "SJF", "Round-robin"],
                "correct_option": "LIFO",
                "topic_tag": "Stacks & Queues",
                "difficulty": "easy",
            },
            {
                "question_text": "A queue exhibits which ordering?",
                "options": ["FIFO", "LIFO", "Priority order", "Random order"],
                "correct_option": "FIFO",
                "topic_tag": "Stacks & Queues",
                "difficulty": "easy",
            },
            {
                "question_text": "Which technique detects a cycle in a linked list?",
                "options": [
                    "Floyd's tortoise and hare",
                    "Binary search",
                    "Bubble sort",
                    "Linear probing",
                ],
                "correct_option": "Floyd's tortoise and hare",
                "topic_tag": "Linked Lists",
                "difficulty": "medium",
            },
            {
                "question_text": "Undo functionality in a text editor is typically implemented with a…",
                "options": ["Stack", "Queue", "Heap", "Hash table"],
                "correct_option": "Stack",
                "topic_tag": "Stacks & Queues",
                "difficulty": "easy",
            },
        ],
    },
    {
        "subject": "Data Structures & Algorithms",
        "teacher": "teacher4@examai.com",
        "topic": "Trees & Graphs",
        "source": "manual",
        "status": "draft",
        "time_limit_seconds": 900,
        "questions": [
            {
                "question_text": "In a binary search tree, the left subtree contains only values that are…",
                "options": ["Less than the node", "Greater than the node", "Equal to the node", "Unordered"],
                "correct_option": "Less than the node",
                "topic_tag": "Trees",
                "difficulty": "easy",
            },
            {
                "question_text": "An in-order traversal of a BST visits values in…",
                "options": ["Sorted order", "Reverse order", "Random order", "Level order"],
                "correct_option": "Sorted order",
                "topic_tag": "Trees",
                "difficulty": "easy",
            },
            {
                "question_text": "Which data structure does breadth-first search use?",
                "options": ["Queue", "Stack", "Priority queue", "Linked list"],
                "correct_option": "Queue",
                "topic_tag": "Graphs",
                "difficulty": "easy",
            },
            {
                "question_text": "An adjacency list is more space-efficient than an adjacency matrix for…",
                "options": ["Sparse graphs", "Complete graphs", "Weighted graphs only", "Directed acyclic graphs only"],
                "correct_option": "Sparse graphs",
                "topic_tag": "Graphs",
                "difficulty": "medium",
            },
            {
                "question_text": "What is the running time of BFS on a graph with V vertices and E edges (adjacency list)?",
                "options": ["O(V + E)", "O(V squared)", "O(E squared)", "O(V log V)"],
                "correct_option": "O(V + E)",
                "topic_tag": "Graphs",
                "difficulty": "medium",
            },
        ],
    },

    # Operating Systems
    {
        "subject": "Operating Systems",
        "teacher": "teacher3@examai.com",
        "topic": "Processes & Threads",
        "source": "manual",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "A process is best described as…",
                "options": [
                    "A program in execution with its own address space",
                    "A file stored on disk",
                    "A running shell script",
                    "A synchronized data structure",
                ],
                "correct_option": "A program in execution with its own address space",
                "topic_tag": "Processes",
                "difficulty": "easy",
            },
            {
                "question_text": "Which of the following is NOT a process state?",
                "options": ["Compiling", "Ready", "Running", "Blocked"],
                "correct_option": "Compiling",
                "topic_tag": "Processes",
                "difficulty": "easy",
            },
            {
                "question_text": "A context switch involves…",
                "options": [
                    "Saving and restoring process state",
                    "Recompiling the kernel",
                    "Defragmenting the disk",
                    "Flushing the CPU cache permanently",
                ],
                "correct_option": "Saving and restoring process state",
                "topic_tag": "Processes",
                "difficulty": "medium",
            },
            {
                "question_text": "Threads within the same process share…",
                "options": ["The address space", "Their stacks", "Their registers", "Their program counters"],
                "correct_option": "The address space",
                "topic_tag": "Threads",
                "difficulty": "easy",
            },
            {
                "question_text": "Thread creation is generally…",
                "options": [
                    "Cheaper than process creation",
                    "More expensive than process creation",
                    "Identical in cost to process creation",
                    "Impossible without root privileges",
                ],
                "correct_option": "Cheaper than process creation",
                "topic_tag": "Threads",
                "difficulty": "easy",
            },
            {
                "question_text": "Which mechanism lets processes exchange data?",
                "options": ["Pipes", "The BIOS", "The page cache only", "File extensions"],
                "correct_option": "Pipes",
                "topic_tag": "Processes",
                "difficulty": "medium",
            },
        ],
    },
    {
        "subject": "Operating Systems",
        "teacher": "teacher4@examai.com",
        "topic": "CPU Scheduling",
        "source": "ai_generated",
        "status": "published",
        "time_limit_seconds": 600,
        "questions": [
            {
                "question_text": "Which scheduling algorithm is non-preemptive and processes jobs in arrival order?",
                "options": ["FCFS", "Round Robin", "SRTF", "Multilevel feedback queue"],
                "correct_option": "FCFS",
                "topic_tag": "Scheduling",
                "difficulty": "easy",
            },
            {
                "question_text": "SJF scheduling minimizes…",
                "options": ["Average waiting time", "Context-switch overhead", "CPU utilization", "Memory usage"],
                "correct_option": "Average waiting time",
                "topic_tag": "Scheduling",
                "difficulty": "medium",
            },
            {
                "question_text": "Round-robin scheduling uses which mechanism to guarantee fairness?",
                "options": ["A time quantum", "A priority ceiling", "A write-ahead log", "A lock-free queue"],
                "correct_option": "A time quantum",
                "topic_tag": "Scheduling",
                "difficulty": "easy",
            },
            {
                "question_text": "Starvation is a known risk of which scheduling approach?",
                "options": ["Priority scheduling", "Round-robin scheduling", "FCFS scheduling", "Random scheduling"],
                "correct_option": "Priority scheduling",
                "topic_tag": "Scheduling",
                "difficulty": "medium",
            },
            {
                "question_text": "The ready queue contains processes that are…",
                "options": [
                    "Ready to run and waiting for the CPU",
                    "Currently blocked on I/O",
                    "Terminated but not reaped",
                    "Waiting for the user to press a key",
                ],
                "correct_option": "Ready to run and waiting for the CPU",
                "topic_tag": "Scheduling",
                "difficulty": "easy",
            },
            {
                "question_text": "What is the convoy effect a problem of?",
                "options": ["FCFS scheduling", "Round-robin scheduling", "Priority aging", "Multilevel queues"],
                "correct_option": "FCFS scheduling",
                "topic_tag": "Scheduling",
                "difficulty": "medium",
            },
        ],
    },
    {
        "subject": "Operating Systems",
        "teacher": "teacher4@examai.com",
        "topic": "Memory Management",
        "source": "manual",
        "status": "draft",
        "time_limit_seconds": 900,
        "questions": [
            {
                "question_text": "Paging divides memory into fixed-size…",
                "options": ["Pages and frames", "Segments and blocks", "Sectors and clusters", "Nodes and edges"],
                "correct_option": "Pages and frames",
                "topic_tag": "Paging",
                "difficulty": "easy",
            },
            {
                "question_text": "Virtual memory allows…",
                "options": [
                    "Running programs larger than physical RAM",
                    "Running two kernels simultaneously",
                    "Storing all data on the GPU",
                    "Eliminating the page table",
                ],
                "correct_option": "Running programs larger than physical RAM",
                "topic_tag": "Virtual Memory",
                "difficulty": "easy",
            },
            {
                "question_text": "Which page replacement algorithm can exhibit Belady's anomaly?",
                "options": ["FIFO", "LRU", "Optimal", "Clock with second chance"],
                "correct_option": "FIFO",
                "topic_tag": "Page Replacement",
                "difficulty": "medium",
            },
            {
                "question_text": "The page table maps…",
                "options": [
                    "Virtual pages to physical frames",
                    "Physical frames to disk sectors",
                    "Files to inodes",
                    "Processes to schedulers",
                ],
                "correct_option": "Virtual pages to physical frames",
                "topic_tag": "Paging",
                "difficulty": "easy",
            },
            {
                "question_text": "Thrashing occurs when the system…",
                "options": [
                    "Spends more time paging than executing",
                    "Runs out of file descriptors",
                    "Has too many cached pages",
                    "Reboots after a kernel panic",
                ],
                "correct_option": "Spends more time paging than executing",
                "topic_tag": "Virtual Memory",
                "difficulty": "medium",
            },
        ],
    },
]

# ── Flashcard decks (student-generated, personal) ─────────────────────────────

# `days_ago` staggers created_at for a realistic deck list. Mastery states are
# valid: new | learning | mastered.
FLASHCARD_DECKS = [
    {
        "student": "student1@examai.com",
        "subject": "Software Engineering",
        "title": "Software Engineering Essentials",
        "days_ago": 18,
        "source_material_filenames": [
            "lecture1_intro_se.pdf",
            "lecture2_agile_scrum.pdf",
            "lecture3_requirements.pdf",
        ],
        "cards": [
            {"front": "What is the classic software development lifecycle?", "back": "Requirements → Design → Implementation → Testing → Maintenance.", "mastery_state": "mastered"},
            {"front": "Name two non-functional requirements.", "back": "Performance (e.g. response time) and security (e.g. encryption).", "mastery_state": "mastered"},
            {"front": "What does plan-driven development mean?", "back": "A detailed, upfront plan where phases complete before implementation begins.", "mastery_state": "learning"},
            {"front": "What is a stakeholder?", "back": "Anyone with an interest in the project: clients, users, managers, regulators.", "mastery_state": "mastered"},
            {"front": "Give an example of a software quality attribute.", "back": "Maintainability — how easily the software can be changed and extended.", "mastery_state": "learning"},
            {"front": "What is an artifact in software engineering?", "back": "A work product of a process, such as a requirements document or design diagram.", "mastery_state": "new"},
            {"front": "Why do large projects need engineering processes?", "back": "To coordinate teams, manage complexity, and produce reliable software on time.", "mastery_state": "learning"},
            {"front": "What is the benefit clause in a user story?", "back": "It makes the underlying business value explicit so the team can prioritize.", "mastery_state": "new"},
            {"front": "What do acceptance criteria define?", "back": "Testable conditions that must hold for a story to be considered done.", "mastery_state": "new"},
            {"front": "What does requirements traceability link?", "back": "Requirements to design, tests, and code for impact analysis.", "mastery_state": "new"},
        ],
    },
    {
        "student": "student1@examai.com",
        "subject": "Data Structures & Algorithms",
        "title": "Data Structures Quick Cards",
        "days_ago": 9,
        "source_material_filenames": [
            "week1_arrays_complexity.pdf",
            "week2_linkedlists_stacks.pdf",
        ],
        "cards": [
            {"front": "What is the time complexity of array index access?", "back": "O(1) — random access.", "mastery_state": "mastered"},
            {"front": "Why does a dynamic array amortize to O(1) append?", "back": "Doubling capacity spreads the occasional O(n) resize across many appends.", "mastery_state": "mastered"},
            {"front": "When is binary search valid?", "back": "Only on a sorted array; worst case O(log n).", "mastery_state": "mastered"},
            {"front": "What does Big-O measure?", "back": "Worst-case growth of time or space as input size n grows.", "mastery_state": "learning"},
            {"front": "What is the space complexity of an n-element array?", "back": "O(n), contiguous allocation.", "mastery_state": "learning"},
            {"front": "Order O(1), O(n), O(n²), O(log n) by growth.", "back": "O(1) < O(log n) < O(n) < O(n²).", "mastery_state": "learning"},
            {"front": "What does a stack's LIFO mean?", "back": "Last In, First Out — the most recently pushed item is popped first.", "mastery_state": "mastered"},
            {"front": "What does a queue's FIFO mean?", "back": "First In, First Out — items leave in the order they arrived.", "mastery_state": "new"},
        ],
    },
    {
        "student": "student2@examai.com",
        "subject": "Advanced Database Systems",
        "title": "Database Fundamentals",
        "days_ago": 21,
        "source_material_filenames": ["ch1_relational_algebra.pdf"],
        "cards": [
            {"front": "What is a relation in the relational model?", "back": "A table with rows (tuples) and named columns (attributes).", "mastery_state": "mastered"},
            {"front": "What does a primary key guarantee?", "back": "Each row is unique and the key is never null.", "mastery_state": "mastered"},
            {"front": "What does selection (σ) do?", "back": "Filters rows by a predicate.", "mastery_state": "mastered"},
            {"front": "What does projection (π) do?", "back": "Selects a subset of columns and removes duplicate rows.", "mastery_state": "learning"},
            {"front": "What is a natural join?", "back": "Combines tables on equally named columns, removing the duplicate join column.", "mastery_state": "learning"},
            {"front": "What does a foreign key enforce?", "back": "Referential integrity — values must exist in the referenced table.", "mastery_state": "mastered"},
            {"front": "What does the HAVING clause do?", "back": "Filters groups produced by GROUP BY (WHERE filters rows first).", "mastery_state": "new"},
            {"front": "Name two relational algebra set operations.", "back": "Union (∪) and set difference (−).", "mastery_state": "new"},
        ],
    },
    {
        "student": "student3@examai.com",
        "subject": "Data Structures & Algorithms",
        "title": "Arrays & Big-O Review",
        "days_ago": 12,
        "source_material_filenames": ["week1_arrays_complexity.pdf"],
        "cards": [
            {"front": "What does O(n) mean?", "back": "Time grows linearly with input size.", "mastery_state": "mastered"},
            {"front": "What does O(1) mean?", "back": "Constant time, independent of input size.", "mastery_state": "mastered"},
            {"front": "Worst-case linear search on an unsorted array?", "back": "O(n).", "mastery_state": "learning"},
            {"front": "Amortized dynamic-array append?", "back": "O(1) amortized thanks to capacity doubling.", "mastery_state": "learning"},
            {"front": "Binary search requires…", "back": "A sorted array.", "mastery_state": "mastered"},
            {"front": "Big-O vs Theta?", "back": "Big-O is an upper bound; Theta is a tight bound.", "mastery_state": "new"},
            {"front": "Why does middle-of-array insertion cost O(n)?", "back": "Elements must be shifted to keep contiguity.", "mastery_state": "learning"},
            {"front": "Which grows faster: n² or n log n?", "back": "n².", "mastery_state": "mastered"},
        ],
    },
    {
        "student": "student5@examai.com",
        "subject": "Operating Systems",
        "title": "Processes & Threads",
        "days_ago": 15,
        "source_material_filenames": ["lec1_processes_threads.pdf"],
        "cards": [
            {"front": "What is a process?", "back": "A program in execution with its own address space, registers, and PCB.", "mastery_state": "mastered"},
            {"front": "Name the main process states.", "back": "New, Ready, Running, Blocked/Waiting, Terminated.", "mastery_state": "learning"},
            {"front": "What happens on a context switch?", "back": "The CPU saves the current process's state and loads another's.", "mastery_state": "learning"},
            {"front": "How do threads differ from processes?", "back": "Threads share the process address space; processes are isolated.", "mastery_state": "mastered"},
            {"front": "Why is thread creation cheaper than process creation?", "back": "No new address space; only stack and registers are allocated.", "mastery_state": "new"},
            {"front": "What is the PCB?", "back": "The Process Control Block — the OS data structure storing process state.", "mastery_state": "mastered"},
            {"front": "Name one IPC mechanism.", "back": "Pipes, message queues, shared memory, or sockets.", "mastery_state": "new"},
            {"front": "When does a process move Running → Ready?", "back": "When preempted by the scheduler or interrupted.", "mastery_state": "learning"},
        ],
    },
    {
        "student": "student5@examai.com",
        "subject": "Advanced Database Systems",
        "title": "SQL & Relational Algebra",
        "days_ago": 6,
        "source_material_filenames": ["ch1_relational_algebra.pdf"],
        "cards": [
            {"front": "What does SELECT map to in relational algebra?", "back": "Projection (π) on columns plus selection (σ) with WHERE.", "mastery_state": "learning"},
            {"front": "What is an INNER JOIN?", "back": "Returns rows matching in both tables on the join condition.", "mastery_state": "mastered"},
            {"front": "What is a LEFT OUTER JOIN?", "back": "All left rows plus matching right rows (NULLs where no match).", "mastery_state": "learning"},
            {"front": "What does GROUP BY do?", "back": "Groups rows so aggregates (COUNT, SUM, AVG) apply per group.", "mastery_state": "learning"},
            {"front": "What is a correlated subquery?", "back": "A subquery that references the outer query's columns.", "mastery_state": "new"},
            {"front": "What does DISTINCT do?", "back": "Removes duplicate rows from the result.", "mastery_state": "mastered"},
            {"front": "What is a view?", "back": "A stored query presented as a virtual table.", "mastery_state": "new"},
            {"front": "What is normalization's goal?", "back": "Reduce redundancy and avoid update anomalies.", "mastery_state": "learning"},
        ],
    },
    {
        "student": "student6@examai.com",
        "subject": "Software Engineering",
        "title": "Agile Terminology",
        "days_ago": 20,
        "source_material_filenames": ["lecture2_agile_scrum.pdf"],
        "cards": [
            {"front": "What is the Agile Manifesto's first value?", "back": "Individuals and interactions over processes and tools.", "mastery_state": "mastered"},
            {"front": "What is a sprint?", "back": "A time-boxed iteration (usually 1–4 weeks) delivering a product increment.", "mastery_state": "mastered"},
            {"front": "Who is the Scrum Master?", "back": "Facilitates the team and removes impediments.", "mastery_state": "mastered"},
            {"front": "Who owns the Product Backlog?", "back": "The Product Owner.", "mastery_state": "learning"},
            {"front": "What is a daily stand-up?", "back": "A short daily meeting to sync on progress and blockers.", "mastery_state": "learning"},
            {"front": "What is the Definition of Done?", "back": "The agreed conditions a completed item must meet.", "mastery_state": "new"},
            {"front": "What is Continuous Integration?", "back": "Frequently merging and automatically testing code changes.", "mastery_state": "learning"},
            {"front": "Name three Scrum artifacts.", "back": "Product Backlog, Sprint Backlog, and the Increment.", "mastery_state": "new"},
        ],
    },
    {
        "student": "student9@examai.com",
        "subject": "Data Structures & Algorithms",
        "title": "Trees & Graphs",
        "days_ago": 4,
        "source_material_filenames": ["week3_trees_graphs.pdf"],
        "cards": [
            {"front": "What is a binary tree?", "back": "A tree in which every node has at most two children.", "mastery_state": "learning"},
            {"front": "What is the BST property?", "back": "Left subtree < node ≤ right subtree by value.", "mastery_state": "mastered"},
            {"front": "What does in-order traversal of a BST produce?", "back": "Values in sorted order.", "mastery_state": "mastered"},
            {"front": "What is a balanced tree?", "back": "Subtree heights differ by at most a constant, keeping ops O(log n).", "mastery_state": "learning"},
            {"front": "Name two graph representations.", "back": "Adjacency list and adjacency matrix.", "mastery_state": "mastered"},
            {"front": "Which is better for sparse graphs?", "back": "Adjacency list (less memory).", "mastery_state": "learning"},
            {"front": "What data structure does BFS use?", "back": "A queue.", "mastery_state": "mastered"},
            {"front": "What data structure does DFS use?", "back": "A stack (explicit or the call stack via recursion).", "mastery_state": "new"},
        ],
    },
    {
        "student": "student11@examai.com",
        "subject": "Operating Systems",
        "title": "CPU Scheduling Basics",
        "days_ago": 11,
        "source_material_filenames": ["lec2_cpu_scheduling.pdf"],
        "cards": [
            {"front": "What is the ready queue?", "back": "Processes that are ready to run and waiting for the CPU.", "mastery_state": "mastered"},
            {"front": "What is FCFS?", "back": "Non-preemptive; first to arrive is served first; can cause a convoy effect.", "mastery_state": "mastered"},
            {"front": "What is SJF?", "back": "Runs the shortest job first, minimizing average waiting time.", "mastery_state": "learning"},
            {"front": "What is Round Robin?", "back": "Preemptive; each process gets a time quantum, then cycles.", "mastery_state": "learning"},
            {"front": "What is a time quantum?", "back": "The fixed CPU slice a process gets per round in round robin.", "mastery_state": "learning"},
            {"front": "What is the risk of priority scheduling?", "back": "Starvation of low-priority processes.", "mastery_state": "learning"},
            {"front": "Which scheduling minimizes average waiting time?", "back": "SJF/SRTF (theoretically).", "mastery_state": "new"},
            {"front": "What does preemptive mean?", "back": "The scheduler can interrupt a running process to switch to another.", "mastery_state": "mastered"},
        ],
    },
    {
        "student": "student14@examai.com",
        "subject": "Advanced Database Systems",
        "title": "Transactions & Concurrency",
        "days_ago": 13,
        "source_material_filenames": ["ch3_transactions_concurrency.pdf"],
        "cards": [
            {"front": "What does ACID stand for?", "back": "Atomicity, Consistency, Isolation, Durability.", "mastery_state": "mastered"},
            {"front": "What does atomicity guarantee?", "back": "The whole transaction commits or the whole transaction rolls back.", "mastery_state": "mastered"},
            {"front": "Name the isolation levels.", "back": "Read Uncommitted, Read Committed, Repeatable Read, Serializable.", "mastery_state": "learning"},
            {"front": "What does two-phase locking prevent?", "back": "Non-serializable schedules; guarantees conflict serializability.", "mastery_state": "new"},
            {"front": "What is a deadlock?", "back": "Two transactions each hold locks the other needs.", "mastery_state": "learning"},
            {"front": "What is write-ahead logging?", "back": "Logging changes before applying them so recovery is possible.", "mastery_state": "learning"},
            {"front": "What is a dirty read?", "back": "Reading data written by an uncommitted transaction.", "mastery_state": "learning"},
            {"front": "How are deadlocks resolved?", "back": "Detection plus rollback of a victim transaction.", "mastery_state": "new"},
        ],
    },
    {
        "student": "student17@examai.com",
        "subject": "Operating Systems",
        "title": "Memory Management",
        "days_ago": 8,
        "source_material_filenames": ["lec3_memory_management.pdf"],
        "cards": [
            {"front": "What is paging?", "back": "Memory divided into fixed-size pages (virtual) and frames (physical).", "mastery_state": "mastered"},
            {"front": "What does the page table map?", "back": "Virtual pages to physical frames.", "mastery_state": "mastered"},
            {"front": "What is the TLB?", "back": "A cache of recent page-table entries speeding address translation.", "mastery_state": "learning"},
            {"front": "What is virtual memory?", "back": "Running programs larger than physical RAM using demand paging.", "mastery_state": "learning"},
            {"front": "Name a page replacement algorithm.", "back": "FIFO, LRU, or Optimal.", "mastery_state": "mastered"},
            {"front": "What is Belady's anomaly?", "back": "FIFO can give MORE page faults with MORE frames.", "mastery_state": "new"},
            {"front": "What is thrashing?", "back": "Excessive paging — more time swapping than executing.", "mastery_state": "learning"},
            {"front": "What is demand paging?", "back": "Loading pages only when they are referenced.", "mastery_state": "learning"},
        ],
    },
    {
        "student": "student20@examai.com",
        "subject": "Data Structures & Algorithms",
        "title": "Linked Lists & Stacks",
        "days_ago": 16,
        "source_material_filenames": ["week2_linkedlists_stacks.pdf"],
        "cards": [
            {"front": "What is in a singly linked list node?", "back": "A value and a pointer to the next node.", "mastery_state": "mastered"},
            {"front": "Head insertion cost?", "back": "O(1).", "mastery_state": "mastered"},
            {"front": "Why is indexing a linked list O(n)?", "back": "No random access; must traverse from the head.", "mastery_state": "learning"},
            {"front": "Doubly linked list advantage?", "back": "O(1) deletion given a pointer to the node (prev link).", "mastery_state": "learning"},
            {"front": "What uses a stack?", "back": "Function calls, undo history, expression evaluation.", "mastery_state": "mastered"},
            {"front": "What uses a queue?", "back": "BFS, buffering, scheduling.", "mastery_state": "learning"},
            {"front": "How to detect a cycle?", "back": "Floyd's tortoise and hare — two pointers at different speeds.", "mastery_state": "new"},
            {"front": "Arrays vs linked lists for traversal?", "back": "Arrays are cache-friendly; linked lists cause pointer chasing.", "mastery_state": "new"},
        ],
    },
    {
        "student": "student22@examai.com",
        "subject": "Advanced Database Systems",
        "title": "Query Optimization",
        "days_ago": 7,
        "source_material_filenames": ["ch2_query_optimization.pdf"],
        "cards": [
            {"front": "What does a query optimizer do?", "back": "Selects the cheapest execution plan for a query.", "mastery_state": "mastered"},
            {"front": "What statistics does it use?", "back": "Table cardinality, column histograms, index selectivity.", "mastery_state": "learning"},
            {"front": "What is a B-tree index?", "back": "A balanced tree supporting O(log n) equality and range lookups.", "mastery_state": "mastered"},
            {"front": "What is a nested-loop join?", "back": "For each outer row, scans the inner relation.", "mastery_state": "learning"},
            {"front": "What is a hash join good for?", "back": "Equi-joins on large tables when no index exists.", "mastery_state": "new"},
            {"front": "What is predicate pushdown?", "back": "Applying filters as early as possible before joins.", "mastery_state": "learning"},
            {"front": "Sequential scan vs index scan?", "back": "Sequential when most rows match; index when few rows match.", "mastery_state": "learning"},
            {"front": "What is an execution plan?", "back": "The tree of operators (scan, join, filter) chosen by the optimizer.", "mastery_state": "mastered"},
        ],
    },
    {
        "student": "student24@examai.com",
        "subject": "Operating Systems",
        "title": "OS Final Review",
        "days_ago": 2,
        "source_material_filenames": [
            "lec2_cpu_scheduling.pdf",
            "lec3_memory_management.pdf",
        ],
        "cards": [
            {"front": "What scheduling algorithm minimizes average waiting time?", "back": "SJF/SRTF.", "mastery_state": "learning"},
            {"front": "How does aging prevent starvation?", "back": "Gradually raising the priority of waiting processes.", "mastery_state": "new"},
            {"front": "What does the page table do?", "back": "Maps virtual pages to physical frames.", "mastery_state": "mastered"},
            {"front": "What caches recent address translations?", "back": "The translation lookaside buffer (TLB).", "mastery_state": "mastered"},
            {"front": "What is demand paging?", "back": "Loading pages only when referenced.", "mastery_state": "learning"},
            {"front": "What is a working set?", "back": "The set of pages a process references in a time window.", "mastery_state": "new"},
            {"front": "What triggers thrashing?", "back": "Working sets exceeding physical memory.", "mastery_state": "new"},
            {"front": "What is the convoy effect?", "back": "Short jobs waiting behind a long job under FCFS.", "mastery_state": "learning"},
        ],
    },
]
